import { IInputTextLabels } from "@/interface/globalInterface";

export const InputFormTextLabels:IInputTextLabels[] = [
  {
    labelName: 'Name',
    id: 'name',
    placeholder: 'Your name here...',
    type: 'text',
    name: 'name',
  },
  {
    labelName: 'Company Email',
    id: 'companyEmail',
    placeholder: 'Your email here...',
    type: 'email',
    name: 'email',
  },
  {
    labelName: 'Skype',
    id: 'skype',
    placeholder: 'Your Skype ID here...',
    type: 'text',
    name: 'skype',
  },
  {
    labelName: 'Choose your program type',
    id: 'programType',
    placeholder: '',
    type: 'select',
    name: 'programType',
    options: [
      {
        id: "1",
        type: 'options1',
        labelName: 'Advertisement Network',
        name: 'advertisementNetwork',
      },
      {
        id: "2",
        type: 'options2',
        labelName: 'Virtual Network',
        name: 'virtualNetwork',
      },
      {
        id: "3",
        type: 'options3',
        labelName: 'Common Network',
        name: 'commonNetwork',
      },
      {
        id: "4",
        type: 'options4',
        labelName: 'Dynamic Network',
        name: 'dynamicNetwork',
      },
      {
        id: "5",
        type: 'options5',
        labelName: 'Static Network',
        name: 'staticNetwork',
      },
    ],
  },
  {
    labelName: 'Advertising Network Name',
    id: 'networkName',
    placeholder: 'Network name here...',
    type: 'text',
    name: 'networkName',
  },
  {
    labelName: 'Network URL',
    id: 'networkURL',
    placeholder: 'Network URL here...',
    type: 'text',
    name: 'networkURL',
  },
  {
    labelName: 'Social Page (Facebook, LinkedIn, Twitter)',
    id: 'socialPage',
    placeholder: 'Social page URLs here...',
    type: 'text',
    name: 'socialPage',
  },
  {
    labelName: 'Network Description',
    id: 'networkDescription',
    placeholder: 'Network description here...',
    type: 'textarea',
    name: 'networkDescription',
  },
  {
    labelName: 'Tags (Ad Network, Ad Server, Ad Exchange, DSP, SSP, RTB, more)',
    id: 'tags',
    placeholder: 'Tags here...',
    type: 'text',
    name: 'tags',
  },
  {
    labelName: 'Commission Type (CPM, CPC, CPA, RevShare, more)',
    id: 'commissionType',
    placeholder: 'Commission type here...',
    type: 'text',
    name: 'commissionType',
  },
  {
    labelName: 'Minimum Payment ($50, $100, more)',
    id: 'minimumPayment',
    placeholder: 'Minimum payment amount here...',
    type: 'text',
    name: 'minimumPayment',
  },
  {
    labelName: 'Payment Frequency (Net-30, Net-15, Weekly, Upon Request, more)',
    id: 'paymentFrequency',
    placeholder: 'Payment frequency here...',
    type: 'text',
    name: 'paymentFrequency',
  },
  {
    labelName: 'Payment Method (Check, PayPal, Wire, more)',
    id: 'paymentMethod',
    placeholder: 'Payment method here...',
    type: 'text',
    name: 'paymentMethod',
  },
  {
    labelName: 'Referral Commission (2%, 5%, None, more)',
    id: 'referralCommissionPublishers',
    placeholder: 'Referral commission here...',
    type: 'text',
    name: 'referralCommissionPublishers',
  },
  {
    labelName: 'Publishers Contact (optional)',
    id: 'PublishersContact',
    placeholder: '',
    type: 'text',
    name: 'PublishersContact',
    options: [
      {
        labelName: 'ex: Email,Skype',
        id: 'PublishersContactDetails1',
        placeholder: 'Contact details here...',
        type: 'text',
        name: 'PublishersContactDetails1',
      },
      {
        labelName: 'ex: Email,Skype',
        id: 'PublishersContactDetails2',
        placeholder: 'Contact details here...',
        type: 'text',
        name: 'PublishersContactDetails2',
      },
    ],
  },

  {
    labelName: 'Ad Format (Native, Push, Popunder, Popup, Video, more)',
    id: 'adFormat',
    placeholder: 'Native, Push, Popunder, Popup, Video, more...',
    type: 'text',
    name: 'adFormat',
  },
  {
    labelName: 'Cost Model (CPM, CPC, more)',
    id: 'costModel',
    placeholder: 'CPM, CPC, more...',
    type: 'text',
    name: 'costModel',
  },
  {
    labelName: 'Minimum Deposit ($50, $100 more)',
    id: 'minimumDeposit',
    placeholder: 'CPM, CPC, more...',
    type: 'text',
    name: 'minimumDeposit',
  },
  {
    labelName: 'Payment Method (Credit Card, PayPal, Wire, more)',
    id: 'paymentMethod',
    placeholder: 'Credit Card, PayPal, Wire, more...',
    type: 'text',
    name: 'paymentMethod',
  },
  {
    labelName: 'Referral Commission (2%, 5%, None, more)',
    id: 'referralCommissionAdvertisers',
    placeholder: '2%, 5%, None, more...',
    type: 'text',
    name: 'referralCommissionAdvertisers',
  },
  {
    labelName: 'Advertisers Contact (optional)',
    id: 'advertisersContact',
    placeholder: '',
    type: 'text',
    name: 'advertisersContact',
    options: [
      {
        labelName: 'ex: Email,Skype',
        id: 'advertisersContactDetails1',
        placeholder: 'Contact details here...',
        type: 'text',
        name: 'advertisersContactDetails1',
      },
      {
        labelName: 'ex: Email,Skype',
        id: 'advertisersContactDetails2',
        placeholder: 'Contact details here...',
        type: 'text',
        name: 'advertisersContactDetails2',
      },
    ],
  },

  {
    labelName: 'Targeting & Optimization:',
    id: 'targetingOptimization',
    placeholder: 'Targeting & Optimization',
    type: '',
    name: 'targetingOptimization',
    options: [
      {
        labelName: 'Self-serve Platform',
        id: 'selfServePlatform',
        type: 'checkbox',
        name: 'selfServePlatform',
      },
      {
        labelName: 'Language Targeting',
        id: 'languageTargeting',
        type: 'checkbox',
        name: 'languageTargeting',
      },
      {
        labelName: 'Device Targeting',
        id: 'deviceTargeting',
        type: 'checkbox',
        name: 'deviceTargeting',
      },
      {
        labelName: 'Category Targeting',
        id: 'categoryTargeting',
        type: 'checkbox',
        name: 'categoryTargeting',
      },
      {
        labelName: 'ISP/Carrier Targeting',
        id: 'ispCarrierTargeting',
        type: 'checkbox',
        name: 'ispCarrierTargeting',
      },
      {
        labelName: 'Retargeting',
        id: 'retargeting',
        type: 'checkbox',
        name: 'retargeting',
      },
      {
        labelName: 'Anti-Fraud',
        id: 'antiFraud',
        type: 'checkbox',
        name: 'antiFraud',
      },
      {
        labelName: 'IP Targeting',
        id: 'ipTargeting',
        type: 'checkbox',
        name: 'ipTargeting',
      },
      {
        labelName: 'Frequency Capping',
        id: 'frequencyCapping',
        type: 'checkbox',
        name: 'frequencyCapping',
      },
      {
        labelName: 'Gambling Ads',
        id: 'gamblingAds',
        type: 'checkbox',
        name: 'gamblingAds',
      },
      {
        labelName: 'GEO Targeting',
        id: 'geoTargeting',
        type: 'checkbox',
        name: 'geoTargeting',
      },
      {
        labelName: 'Time Targeting',
        id: 'timeTargeting',
        type: 'checkbox',
        name: 'timeTargeting',
      },
      {
        labelName: 'OS Targeting',
        id: 'osTargeting',
        type: 'checkbox',
        name: 'osTargeting',
      },
      {
        labelName: 'Demographic Targeting',
        id: 'demographicTargeting',
        type: 'checkbox',
        name: 'demographicTargeting',
      },
      {
        labelName: 'Browser Targeting',
        id: 'browserTargeting',
        type: 'checkbox',
        name: 'browserTargeting',
      },
      {
        labelName: 'Black/White List',
        id: 'blackWhiteList',
        type: 'checkbox',
        name: 'blackWhiteList',
      },
      {
        labelName: 'Adult Ads',
        id: 'adultAds',
        type: 'checkbox',
        name: 'adultAds',
      },
      {
        labelName: 'Website Targeting',
        id: 'websiteTargeting',
        type: 'checkbox',
        name: 'websiteTargeting',
      },
      {
        labelName: 'Token',
        id: 'token',
        type: 'checkbox',
        name: 'token',
      },
      {
        labelName: 'Personal Account Manager',
        id: 'personalAccountManager',
        type: 'checkbox',
        name: 'personalAccountManager',
      },
    ],
  },
  {
    labelName: 'Top GEO (US, RU, UK, CA, IN, BR, WorldWide, more)',
    id: 'topGeo',
    placeholder: 'US, RU, UK, CA, IN, BR, WorldWide, more...',
    type: 'text',
    name: 'topGeo',
  },
  {
    labelName:
      'Top Vertical (Dating, Sweepstakes, Mobile App, Health/Nutra, Forex, more)',
    id: 'topVertical',
    placeholder: 'Dating, Sweepstakes, Mobile App...',
    type: 'text',
    name: 'topVertical',
  },
  {
    labelName: 'Referral Commission (2%, 5%, None, more)',
    id: 'refCommission',
    placeholder: '2%, 5%, None, more...',
    type: 'text',
    name: 'refCommission',
  },
  {
    labelName: 'Please let us know if you have any other questions (optional)',
    id: 'faq',
    placeholder: '',
    type: 'textarea',
    name: 'faq',
  },
];
