export type OffersType = {
  _id: number;
  image: string;
  title: string;
  tag: string;
  categories: string[];
  price: number;
  countries: string[];
  vertical: string;
};

export const OffersData = [
  {
    _id: 1,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 2,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 3,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 4,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 5,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 6,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 7,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 8,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 9,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 10,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 11,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 12,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 13,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 14,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 15,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 16,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 17,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 18,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 19,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 20,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 21,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
  {
    _id: 22,
    image: '/Offer/OfferDataImage.svg',
    title: 'Sweeptakes - Mob/ Web/ Tab',
    tag: 'TopClientOffer',
    categories: ['SOI,DOI', 'SALES'],
    price: 10,
    countries: ['US', 'CA', 'UK', 'AU', 'IT', 'DE'],
    vertical: 'Sweeptakes',
  },
];


export const customAds = [
  {
    image: '/Offer/ad1.png',
  },
  {
    image: '/Offer/ad2.png',
  },
  {
    image: '/Offer/ad3.png',
  },
  {
    image: '/Offer/ad4.png',
  },
  {
    image: '/Offer/ad5.png',
  },
];
