export const StartNetworksData = [
  {
    image: '/Home/star_networks/1.svg',
    name: 'TopClientOffer',
    category: ['Dating', 'Sweeptakes'],
    totalRatings: 101,
    ratings: '/Home/star_networks/ratings.svg',
  },
  {
    image: '/Home/star_networks/2.svg',
    name: 'Affmine',
    category: ['Dating', 'Sweeptakes'],
    totalRatings: 102,
    ratings: '/Home/star_networks/ratings.svg',
  },
  {
    image: '/Home/star_networks/3.svg',
    name: 'Algo-Affiliates',
    category: ['Dating', 'Sweeptakes'],
    totalRatings: 103,
    ratings: '/Home/star_networks/ratings.svg',
  },
  {
    image: '/Home/star_networks/4.svg',
    name: 'Leadbit',
    category: ['Dating', 'Sweeptakes'],
    totalRatings: 1043,
    ratings: '/Home/star_networks/ratings.svg',
  },
  {
    image: '/Home/star_networks/5.svg',
    name: 'Leadbit',
    category: ['Dating', 'Sweeptakes'],
    totalRatings: 1043,
    ratings: '/Home/star_networks/ratings.svg',
  },
  {
    image: '/Home/star_networks/1.svg',
    name: 'Leadbit',
    category: ['Dating', 'Sweeptakes'],
    totalRatings: 210,
    ratings: '/Home/star_networks/ratings.svg',
  },
  {
    image: '/Home/star_networks/2.svg',
    name: 'Leadbit',
    category: ['Dating', 'Sweeptakes'],
    totalRatings: 510,
    ratings: '/Home/star_networks/ratings.svg',
  },
  {
    image: '/Home/star_networks/3.svg',
    name: 'Leadbit',
    category: ['Dating', 'Sweeptakes'],
    totalRatings: 150,
    ratings: '/Home/star_networks/ratings.svg',
  },
  {
    image: '/Home/star_networks/4.svg',
    name: 'Dao.AD',
    category: ['Dating', 'Sweeptakes'],
    totalRatings: 150,
    ratings: '/Home/star_networks/ratings.svg',
  },
];
